# Generated by Django 6.1.1 on 2026-09-14 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attendee',
            name='institution_other',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='eventbrand',
            name='auto_theme',
            field=models.BooleanField(default=True, help_text='When on, adding a logo re-derives the theme colors from the logo.'),
        ),
        migrations.AddField(
            model_name='eventbrand',
            name='logo_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', help_text='Alignment of the logo row on the event and check-in pages.', max_length=10),
        ),
        migrations.AddField(
            model_name='attendee',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendees', to='Events.institution'),
        ),
        migrations.AddField(
            model_name='event',
            name='attending_institutions',
            field=models.ManyToManyField(blank=True, related_name='events', to='Events.institution'),
        ),
    ]
