# Generated by Django 6.1.1 on 2026-09-14 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_institution_attendee_institution_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='checked_in_afternoon_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='checked_in_morning_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='afternoon_label',
            field=models.CharField(blank=True, default='Afternoon', max_length=40),
        ),
        migrations.AddField(
            model_name='event',
            name='morning_label',
            field=models.CharField(blank=True, default='Morning', max_length=40),
        ),
        migrations.AddField(
            model_name='event',
            name='sessions',
            field=models.CharField(choices=[('single', 'Single session (all-day)'), ('split', 'Morning & afternoon')], default='single', help_text='Split the day into separate morning and afternoon check-ins.', max_length=10),
        ),
        migrations.CreateModel(
            name='MeetingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('document', 'Document'), ('instructions', 'Instructions'), ('wifi', 'Wi-Fi'), ('rooms', 'Rooms'), ('itinerary', 'Itinerary'), ('programme', 'Programme')], default='document', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='materials/')),
                ('link', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='Events.event')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
