# Generated by Django 6.1.1 on 2026-09-15 06:32

import django.db.models.deletion
from django.db import migrations, models


def move_session_fields(apps, schema_editor):
    """Backfill AttendanceLog rows from the per-session attendee timestamps
    so no existing morning/afternoon check-in data is lost."""
    Attendee = apps.get_model("Events", "Attendee")
    AttendanceLog = apps.get_model("Events", "AttendanceLog")
    for att in Attendee.objects.filter(checked_in_morning_at__isnull=False):
        AttendanceLog.objects.create(
            attendee=att,
            day=att.event.date or att.checked_in_morning_at.date(),
            session="morning",
            checked_in_at=att.checked_in_morning_at,
        )
    for att in Attendee.objects.filter(checked_in_afternoon_at__isnull=False):
        AttendanceLog.objects.create(
            attendee=att,
            day=att.event.date or att.checked_in_afternoon_at.date(),
            session="afternoon",
            checked_in_at=att.checked_in_afternoon_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_attendee_checked_in_afternoon_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('session', models.CharField(choices=[('single', 'Single'), ('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=10)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='Events.attendee')),
            ],
            options={
                'ordering': ['day', 'session'],
                'unique_together': {('attendee', 'day', 'session')},
            },
        ),
        migrations.RunPython(move_session_fields, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='attendee',
            name='checked_in_afternoon_at',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='checked_in_morning_at',
        ),
    ]